[project]
name = "read-ublox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "pygnssutils>=1.1.16",
    "pyubx2>=1.2.55",
    "serial>=0.0.97",
]
